### PR TITLE
Arrow pagination

### LINKED ISSUE #20: restyle prev/next navigation arrows
To mimic the pattern used by open source project https://github.com/rstudio/bookdown

### PR DESCRIPTION
**Pull request by lukebaker**
Fixes #20

### CODE REVIEW

**Comment by msalganik** [comment]
Thanks @lukebaker.  The functionality is great.

One design change, could you make them arrows a bit  "softer"?  For example, could they be a shade of grey that is closer to white and/or could they be thinner? 

Also, does this mean that we remove the navigation at the bottom of each page?  I think so.  Can you comment out that part of the code so we can see what it looks like without them.  But we might want to add them back in.

**Comment by lukebaker** [comment]
> One design change, could you make them arrows a bit "softer"? For example, could they be a shade of grey that is closer to white and/or could they be thinner?

Sure thing. I switched to the Bootstrap menu icon from the chevron icon. Is that better?

> Also, does this mean that we remove the navigation at the bottom of each page? I think so. Can you comment out that part of the code so we can see what it looks like without them. But we might want to add them back in.

I've also removed that.

How does that look here: https://a8137d4f.ngrok.io/en/introduction/figures/

**Comment by msalganik** [comment]
Great.  I like both changes.  Please merge when you think it is ready.

**Comment by lukebaker** [comment]
@msalganik, these changes are merged into master of Open Review Toolkit and you can see them reflected on the [sample site](http://sample.openreviewtoolkit.org/). Do you want me to port these changes to the Bit By Bit site?

**Comment by msalganik** [comment]
No thanks.  Let's leave Bit by Bit as is for now, and then we will get all these improvements when we rebuild for the first edition of the book.

**Pull request merged**
